# Generated by Django 4.1.3 on 2022-11-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='TODO name', max_length=2, null=True)),
                ('image', models.ImageField(help_text='TODO image', max_length=200, upload_to='todos/')),
                ('desc', models.TextField(default='', help_text='TODO description', max_length=200, verbose_name='TODO description')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOinfo',
                'db_table': 'todo',
                'managed': True,
            },
        ),
    ]
