# Generated by Django 4.1.3 on 2022-11-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_todo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': True, 'verbose_name': 'TODO', 'verbose_name_plural': 'Todo'},
        ),
    ]
