# Generated by Django 4.1.3 on 2022-11-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_title_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
